//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace git2ftp_mvc5.App_Code.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class git2ftp_Users
    {
        public git2ftp_Users()
        {
            this.git2ftp_Projects = new HashSet<git2ftp_Projects>();
        }
    
        public int pKey { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<git2ftp_Projects> git2ftp_Projects { get; set; }
    }
}
