//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace git2ftp_mvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class git2ftp_Log
    {
        public int pKey { get; set; }
        public int ProjectID { get; set; }
        public string GitHubJSON { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string State { get; set; }
    
        public virtual git2ftp_Projects git2ftp_Projects { get; set; }
    }
}
